package utils

var BaiDuLang = map[string]string{
	"auto":  "auto",
	"zh_cn": "zh",
	"zh_tw": "cht",
	"yue":   "yue",
	"en":    "en",
	"ja":    "jp",
	"ko":    "kor",
	"fr":    "fra",
	"es":    "spa",
	"ru":    "ru",
	"de":    "de",
	"it":    "it",
	"tr":    "tr",
	"pt_pt": "pt",
	"pt_br": "pot",
	"vi":    "vie",
	"id":    "id",
	"th":    "th",
	"ms":    "may",
	"ar":    "ar",
	"hi":    "hi",
	"km":    "hkm",
	"nb_no": "nob",
	"nn_no": "nno",
	"fa":    "per",
}

var YouDaoLang = map[string]string{
	"auto":  "auto",
	"zh_cn": "zh-CHS",
	"zh_tw": "zh-CHT",
	"yue":   "yue",
	"en":    "en",
	"ja":    "jp",
	"ko":    "kor",
	"fr":    "fra",
	"es":    "spa",
	"ru":    "ru",
	"de":    "de",
	"it":    "it",
	"tr":    "tr",
	"pt_pt": "pt",
	"pt_br": "pt",
	"vi":    "vie",
	"id":    "id",
	"th":    "th",
	"ms":    "may",
	"ar":    "ar",
	"hi":    "hi",
	"mn_mo": "mn",
	"km":    "km",
	"nb_no": "no",
	"nn_no": "no",
	"fa":    "fa",
}
